authorization_sync_job:
  cron: '0 10 * * *'
  class: AuthorizationSyncJob
  description: 'This job syncs the authorizations database to the blockchain'

vote_sync_job:
  cron: '30 10 * * *'
  class: VoteSyncJob
  description: 'This job syncs the votes database to the blockchain'